# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1575, 987)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.bottomLayout = QtWidgets.QGridLayout()
        self.bottomLayout.setObjectName("bottomLayout")
        self.dislikeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.dislikeBtn.setObjectName("dislikeBtn")
        self.bottomLayout.addWidget(self.dislikeBtn, 1, 0, 1, 1)
        self.likeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.likeBtn.setObjectName("likeBtn")
        self.bottomLayout.addWidget(self.likeBtn, 0, 0, 1, 1)
        self.previousBtn = QtWidgets.QPushButton(self.centralwidget)
        self.previousBtn.setObjectName("previousBtn")
        self.bottomLayout.addWidget(self.previousBtn, 0, 2, 1, 1)
        self.nextBtn = QtWidgets.QPushButton(self.centralwidget)
        self.nextBtn.setObjectName("nextBtn")
        self.bottomLayout.addWidget(self.nextBtn, 0, 3, 1, 1)
        self.prevPostBtn = QtWidgets.QPushButton(self.centralwidget)
        self.prevPostBtn.setObjectName("prevPostBtn")
        self.bottomLayout.addWidget(self.prevPostBtn, 1, 2, 1, 1)
        self.nextPostBtn = QtWidgets.QPushButton(self.centralwidget)
        self.nextPostBtn.setObjectName("nextPostBtn")
        self.bottomLayout.addWidget(self.nextPostBtn, 1, 3, 1, 1)
        self.infoText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.infoText.setReadOnly(True)
        self.infoText.setBackgroundVisible(False)
        self.infoText.setCenterOnScroll(False)
        self.infoText.setObjectName("infoText")
        self.bottomLayout.addWidget(self.infoText, 0, 1, 2, 1)
        self.gridLayout.addLayout(self.bottomLayout, 4, 0, 1, 1)
        self.topLayout = QtWidgets.QGridLayout()
        self.topLayout.setObjectName("topLayout")
        self.subredditEntry = QtWidgets.QLineEdit(self.centralwidget)
        self.subredditEntry.setObjectName("subredditEntry")
        self.topLayout.addWidget(self.subredditEntry, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.topLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.postIDEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.postIDEdit.sizePolicy().hasHeightForWidth())
        self.postIDEdit.setSizePolicy(sizePolicy)
        self.postIDEdit.setInputMask("")
        self.postIDEdit.setObjectName("postIDEdit")
        self.topLayout.addWidget(self.postIDEdit, 0, 1, 1, 1)
        self.previewBtn = QtWidgets.QPushButton(self.centralwidget)
        self.previewBtn.setObjectName("previewBtn")
        self.topLayout.addWidget(self.previewBtn, 0, 4, 1, 1)
        self.filterGroup = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterGroup.sizePolicy().hasHeightForWidth())
        self.filterGroup.setSizePolicy(sizePolicy)
        self.filterGroup.setMaximumSize(QtCore.QSize(16777215, 100))
        self.filterGroup.setCheckable(True)
        self.filterGroup.setChecked(False)
        self.filterGroup.setObjectName("filterGroup")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.filterGroup)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nsfwCheck = QtWidgets.QCheckBox(self.filterGroup)
        self.nsfwCheck.setChecked(False)
        self.nsfwCheck.setObjectName("nsfwCheck")
        self.horizontalLayout.addWidget(self.nsfwCheck)
        self.sfwCheck = QtWidgets.QCheckBox(self.filterGroup)
        self.sfwCheck.setObjectName("sfwCheck")
        self.horizontalLayout.addWidget(self.sfwCheck)
        self.skipCheck = QtWidgets.QCheckBox(self.filterGroup)
        self.skipCheck.setObjectName("skipCheck")
        self.horizontalLayout.addWidget(self.skipCheck)
        self.nonImageCheck = QtWidgets.QCheckBox(self.filterGroup)
        self.nonImageCheck.setObjectName("nonImageCheck")
        self.horizontalLayout.addWidget(self.nonImageCheck)
        self.keywordEntry = QtWidgets.QLineEdit(self.filterGroup)
        self.keywordEntry.setObjectName("keywordEntry")
        self.horizontalLayout.addWidget(self.keywordEntry)
        self.topLayout.addWidget(self.filterGroup, 1, 0, 1, 4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.topLayout.addWidget(self.label, 0, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.stepSpinner = QtWidgets.QSpinBox(self.centralwidget)
        self.stepSpinner.setMinimum(1)
        self.stepSpinner.setProperty("value", 8)
        self.stepSpinner.setObjectName("stepSpinner")
        self.gridLayout_2.addWidget(self.stepSpinner, 1, 1, 1, 1)
        self.idLabel = QtWidgets.QLabel(self.centralwidget)
        self.idLabel.setObjectName("idLabel")
        self.gridLayout_2.addWidget(self.idLabel, 0, 0, 1, 2)
        self.topLayout.addLayout(self.gridLayout_2, 1, 4, 1, 1)
        self.gridLayout.addLayout(self.topLayout, 0, 0, 1, 1)
        self.centerLayout = QtWidgets.QGridLayout()
        self.centerLayout.setObjectName("centerLayout")
        self.webView = QtWebKitWidgets.QWebView(self.centralwidget)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.centerLayout.addWidget(self.webView, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.centerLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1675, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.saveAction = QtWidgets.QAction(MainWindow)
        self.saveAction.setObjectName("saveAction")
        self.setLastAction = QtWidgets.QAction(MainWindow)
        self.setLastAction.setObjectName("setLastAction")
        self.menuFile.addAction(self.saveAction)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dislikeBtn.setText(_translate("MainWindow", "Dislike"))
        self.likeBtn.setText(_translate("MainWindow", "Like"))
        self.previousBtn.setText(_translate("MainWindow", "Previous"))
        self.nextBtn.setText(_translate("MainWindow", "Next"))
        self.prevPostBtn.setText(_translate("MainWindow", "Previous Post"))
        self.nextPostBtn.setText(_translate("MainWindow", "Next Post"))
        self.infoText.setPlainText(_translate("MainWindow", "Post Information"))
        self.subredditEntry.setText(_translate("MainWindow", "wallpaperdump"))
        self.label_2.setText(_translate("MainWindow", "Post ID"))
        self.previewBtn.setText(_translate("MainWindow", "Preview"))
        self.filterGroup.setTitle(_translate("MainWindow", "Filter"))
        self.nsfwCheck.setText(_translate("MainWindow", "NSFW"))
        self.sfwCheck.setText(_translate("MainWindow", "SFW only"))
        self.skipCheck.setText(_translate("MainWindow", "Skip rated"))
        self.nonImageCheck.setText(_translate("MainWindow", "Include non-images"))
        self.keywordEntry.setPlaceholderText(_translate("MainWindow", "Title contains"))
        self.label.setText(_translate("MainWindow", "Subreddit"))
        self.label_3.setText(_translate("MainWindow", "Step Time:"))
        self.idLabel.setText(_translate("MainWindow", "Image ID: -1"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.saveAction.setText(_translate("MainWindow", "Save Image"))
        self.setLastAction.setText(_translate("MainWindow", "Set Last ID"))

from PyQt5 import QtWebKitWidgets